### ISSUE TITLE
Authentification stopped working for Fiducia/GAD 

### ISSUE THREAD

**Issue by gruban** [fintastic/hbci#18]
Since today I'm getting error messages when trying to get data from the GLS Bank (which uses the Fiducia/GAD systems):
HIRMG:3:2+9050::Die Nachricht enth?lt Fehler.'
HIRMS:4:2:3+9075::Starke Kundenauthentifizierung notwendig.'

However I can retrieve my transactions using Fints via Starmoney with only UserId and PIN. Looking at the FinTS response in the Starmoney log I can see this response to the authentification:
HIRMG:3:2+3060::Bitte beachten Sie die enthaltenen Warnungen/Hinweise.'
HIRMS:4:2:4+3920::Zugelassene TAN-Verfahren f.r den Benutzer:942+0901::*PIN g.ltig.+0020::*Dialoginitialisierung erfolgreich'
HIRMS:5:2:5+3076::Starke Kundenauthentifizierung nicht notwendig.'
HITAN:6:6:5+4++noref+nochallenge'

Looking at request in Starmoney I can also see the the segment "HKTAN:5:6+4+HKIDN'" was sent - I'm just guessing if this might be missing?

**Comment by aklaiber** [comment]
sorry, I need longer as expected for this fix. A simply HKTAN segment is unfortunately not enough.

**Comment by gruban** [comment]
Thank you for working on it, @aklaiber ! I can imagine it's not so simple as the dialogue has to offer the option to add two factor authentification TAN as the bank is required to query at least once every 90 days.

**Comment by aklaiber** [comment]
It works now with https://github.com/fintastic/hbci/pull/19 but in my opinion I have to do a bigger refactoring to get a solid HBCI lib.
