### ISSUE TITLE
Not registered as FinTS-Product error

### ISSUE THREAD

**Issue by gruban** [fintastic/hbci#21]
Thank you for the fix to #18 - while trying to test it I got a new error:
"9800::Dialog abgebrochen+9078::Software nicht als FinTS-Produkt registriert. Bitte an Hersteller wenden."

Is this library registered as product or should I register as developer? In that case how to I send "Produktbezeichnung" and "Produktversion" [as required](https://www.hbci-zka.de/register/prod_register.htm)?

**Comment by aklaiber** [comment]
Could you send me the log output?

**Comment by gruban** [comment]
This is it (personal information replaced):

> I, [2019-11-02T23:07:40.925949 #28822]  INFO -- : Start initiating FinTS/HBCI session
> D, [2019-11-02T23:07:40.929130 #28822] DEBUG -- : Request: HNHBK:1:3+000000000372+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20191102:231140+2:2:13:@5@NOKEY:5:1+280:43060967:{USERID}:V:1:1+0'HNVSD:999:1+@215@HNSHK:2:4+PIN:1+999+12999988+1+1+1::0+2+1:20191102:231140+1:999:1+6:10:16+280:43060967:{USERID}:S:0:0'HKIDN:3:2+280:43060967+{USERID}+0+1'HKVVB:4:3+0+0+1+FintasticHBCI+0.3.5'HKSYN:5:3+0'HNSHA:6:2+12999988++{PIN}''HNHBS:7:1+1'
> D, [2019-11-02T23:07:41.089195 #28822] DEBUG -- : Response: HNHBK:1:3+000000000226+300+M19110223074119+1+M19110223074119:1'HIRMG:2:2+9050::Die Nachricht enth?lt Fehler.+9800::Dialog abgebrochen+9078::Software nicht als FinTS-Produkt registriert. Bitte an Hersteller wenden.'HNHBS:3:1+1'
> Hbci::DialogError: Session Initialization failed

**Comment by aklaiber** [comment]
It is a change because of the PSD2 policies. Unfortunately you have to register a "FinTS-Produkt". 

https://vrkennung.de/die-psd2-erfordert-registrierung-und-aktualitaet-der-zahlungsverkehrsprogramme/

**Comment by gruban** [comment]
Right, but in the dialogue I need to send the "Produktbezeichnung":

> Die Registrierungsnummer ist ab dem 1.12.2018 bei jeder Dialoginitialisierung in das Element Produktbezeichnung einzustellen.
[https://www.hbci-zka.de/register/prod_register.htm](https://www.hbci-zka.de/register/prod_register.htm)

I would expect to be able to set this in the BankCredentials::Hbci

**Comment by aklaiber** [comment]
Yes correct, I have to change this but in the meanwhile you can change the value in the HKVVB Segment.   

https://github.com/fintastic/hbci/blob/master/lib/hbci/dialog.rb#L61
https://github.com/fintastic/hbci/blob/master/lib/hbci/segments/hkvvb.rb#L10

**Comment by agross** [comment]
Seems like OSS libs got their ID assigned without issues:

https://github.com/mrklintscher/libfintx/issues/53

**Comment by gruban** [comment]
For us too - just had to fill out the form and wait for a few days.
