### ISSUE TITLE
Issues with netbank and BalanceReceiver

### ISSUE THREAD

**Issue by agross** [fintastic/hbci#8]
The following code throws `NoMethodError: undefined method `build' for nil:NilClass` because netbank uses `hksal` version 5 (whatever that is!)

```
require 'hbci'
CREDENTIALS = BankCredentials::Hbci.new(
  url:       'https://banking.netbank.de/hbci',
  bank_code: 20_090_500.to_s,
  user_id:   '123',
  pin:       'secret'
)

IBAN = 'DE41 2009 0500 0001 1234 56'.tr(' ', '').freeze

balance = 0
Hbci::Connector.open(CREDENTIALS) do |connector|
  Hbci::Dialog.open(connector) do |dialog|
    balance = Hbci::Services::BalanceReceiver.new(connector, dialog, IBAN).perform
  end
end

balance.to_f
```

I added a `puts version` to `BalanceReceiver#build_hksal` and it logged `5` which is currently not supported. It would be great if you could add support for this version.

**Comment by aklaiber** [comment]
Apologize for the late response. I'll try to Implement hksal version 5 as soon as possible.

**Comment by agross** [comment]
:+1:Thank you for looking into this!

**Comment by aklaiber** [comment]
https://github.com/fintastic/hbci/pull/9
